# 🔢 Complete NumPy Operations Guide
### Every NumPy Topic with Theory + Examples
---

In [2]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 2.3.5


## 1️⃣ Array Creation

In [2]:
# np.array() converts Python list/tuple into a NumPy array
a = np.array([1, 2, 3, 4, 5])
print('1D Array:', a)

# 2D array created from nested lists — forms a matrix
b = np.array([[1,2,3],[4,5,6]])
print('2D Array:\n', b)

# np.zeros() creates array filled with 0.0 — useful for initialization
print('Zeros:', np.zeros((2,3)))

# np.ones() creates array filled with 1.0
print('Ones:', np.ones((2,3)))

# np.full() fills array with a custom constant value
print('Full:', np.full((2,3), 7))

# np.eye() creates an identity matrix with 1s on the diagonal
print('Identity:\n', np.eye(3))

# np.arange() generates evenly spaced values within a given interval (like Python range)
print('Arange:', np.arange(0, 10, 2))

# np.linspace() returns N evenly spaced values between start and stop inclusive
print('Linspace:', np.linspace(0, 1, 5))

# np.empty() allocates array memory without initializing — fast but values are garbage
print('Empty:\n', np.empty((2,2)))

# np.random.rand() fills array with random floats in [0, 1)
print('Random:', np.random.rand(2,3))

# np.random.randint() generates random integers in a specified range
print('RandInt:', np.random.randint(1, 10, size=(2,3)))

# np.random.randn() returns samples from standard normal distribution (mean=0, std=1)
print('RandN:', np.random.randn(2,3))

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Full: [[7 7 7]
 [7 7 7]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Empty:
 [[0.25 0.5 ]
 [0.75 1.  ]]
Random: [[0.76330661 0.74930367 0.97505711]
 [0.54138584 0.5044354  0.23232622]]
RandInt: [[1 9 7]
 [8 3 8]]
RandN: [[-0.36471063  0.89805888 -0.42456672]
 [ 0.41390966 -0.81644    -1.01171785]]


## 2️⃣ Array Attributes

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

# .ndim gives the number of dimensions (axes) of the array
print('ndim:', arr.ndim)

# .shape returns a tuple (rows, cols) — the size along each dimension
print('shape:', arr.shape)

# .size gives total number of elements in the array
print('size:', arr.size)

# .dtype tells the data type of elements (int64, float64, etc.)
print('dtype:', arr.dtype)

# .itemsize shows number of bytes consumed by a single element
print('itemsize:', arr.itemsize, 'bytes')

# .nbytes is the total memory consumed by the array in bytes
print('nbytes:', arr.nbytes, 'bytes')

ndim: 2
shape: (2, 3)
size: 6
dtype: int64
itemsize: 8 bytes
nbytes: 48 bytes


## 3️⃣ Data Types (dtype)

In [4]:
# Specify dtype at creation to control memory usage and precision
a_int   = np.array([1,2,3], dtype=np.int32)
a_float = np.array([1,2,3], dtype=np.float64)
a_bool  = np.array([1,0,1], dtype=np.bool_)
a_cmplx = np.array([1+2j, 3+4j], dtype=np.complex128)
print('int32:',   a_int,   a_int.dtype)
print('float64:', a_float, a_float.dtype)
print('bool:',    a_bool,  a_bool.dtype)
print('complex:', a_cmplx, a_cmplx.dtype)

# .astype() casts an existing array to a new data type without modifying original
a_cast = a_int.astype(np.float32)
print('Cast to float32:', a_cast, a_cast.dtype)

int32: [1 2 3] int32
float64: [1. 2. 3.] float64
bool: [ True False  True] bool
complex: [1.+2.j 3.+4.j] complex128
Cast to float32: [1. 2. 3.] float32


## 4️⃣ Indexing & Slicing

In [5]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print('Array:\n', arr)

# Basic indexing: arr[row, col] — access a single element
print('Element [1,2]:', arr[1,2])

# Slicing rows: arr[start:stop] — extracts a sub-array of rows
print('Rows 0-1:\n', arr[0:2])

# Slicing both axes: arr[rows, cols]
print('Sub-matrix:\n', arr[0:2, 1:3])

# Fancy indexing: pass a list of indices to select specific rows/elements
print('Fancy rows:', arr[[0,2]])

# Negative indexing: -1 means last element, -2 second to last, etc.
print('Last row:', arr[-1])

# Boolean indexing: select elements where condition is True
print('Elements > 40:', arr[arr > 40])

# np.where() returns indices where condition is True (row, col arrays)
print('Where > 40:', np.where(arr > 40))

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element [1,2]: 60
Rows 0-1:
 [[10 20 30]
 [40 50 60]]
Sub-matrix:
 [[20 30]
 [50 60]]
Fancy rows: [[10 20 30]
 [70 80 90]]
Last row: [70 80 90]
Elements > 40: [50 60 70 80 90]
Where > 40: (array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


## 5️⃣ Reshaping & Manipulation

In [3]:
arr = np.arange(1, 13)
print('Original:', arr)

# .reshape() changes shape without changing data — total elements must remain same
print('Reshaped (3x4):\n', arr.reshape(3,4))

# .flatten() returns a 1D copy of the array regardless of original shape
mat = arr.reshape(3,4)
print('Flattened:', mat.flatten())

# .ravel() also returns 1D but returns a view when possible (memory efficient)
print('Raveled:', mat.ravel())

# .T or .transpose() flips rows and columns of a matrix
print('Transposed:\n', mat.T)

# np.expand_dims() adds a new axis — useful for broadcasting compatibility
a = np.array([1,2,3])
print('Expand axis=0:', np.expand_dims(a, axis=0).shape)  # (1,3)
print('Expand axis=1:', np.expand_dims(a, axis=1).shape)  # (3,1)

# np.squeeze() removes axes of size 1 from array shape
b = np.array([[[1],[2],[3]]])
print('Squeezed:', np.squeeze(b).shape)

# np.swapaxes() swaps two specific axes of an array
print('Swapaxes:', mat.swapaxes(0,1).shape)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Expand axis=0: (1, 3)
Expand axis=1: (3, 1)
Squeezed: (3,)
Swapaxes: (4, 3)


## 6️⃣ Joining & Splitting Arrays

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# np.concatenate() joins arrays along an existing axis
print('Concat axis=0:\n', np.concatenate([a,b], axis=0))
print('Concat axis=1:\n', np.concatenate([a,b], axis=1))

# np.vstack() stacks arrays vertically (row-wise) — same as concat axis=0
print('vstack:\n', np.vstack([a,b]))

# np.hstack() stacks arrays horizontally (column-wise) — same as concat axis=1
print('hstack:\n', np.hstack([a,b]))

# np.dstack() stacks along the third axis (depth)
print('dstack shape:', np.dstack([a,b]).shape)

# np.stack() joins arrays along a NEW axis
print('stack axis=0 shape:', np.stack([a,b], axis=0).shape)

# np.split() divides an array into equal sub-arrays along a given axis
arr = np.arange(12).reshape(4,3)
parts = np.split(arr, 2, axis=0)
print('Split parts:', [p.shape for p in parts])

# np.hsplit() splits array column-wise; np.vsplit() splits row-wise
print('hsplit:', [p.shape for p in np.hsplit(arr, 3)])
print('vsplit:', [p.shape for p in np.vsplit(arr, 4)])

## 7️⃣ Mathematical Operations

In [8]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Arithmetic operations are element-wise by default
print('Add:', a + b)
print('Sub:', a - b)
print('Mul:', a * b)
print('Div:', a / b)
print('Floor Div:', a // b)
print('Mod:', a % b)
print('Power:', a ** 2)

# np.add, np.subtract etc. are ufuncs (universal functions) — same as operators
print('np.add:', np.add(a, b))
print('np.multiply:', np.multiply(a, b))

# np.sqrt() computes element-wise square root
print('sqrt:', np.sqrt(a))

# np.exp() computes e^x for each element
print('exp:', np.exp(b))

# np.log() natural log; np.log2() base-2 log; np.log10() base-10 log
print('log:', np.log(a))
print('log2:', np.log2(a))
print('log10:', np.log10(a))

# np.abs() returns absolute (positive) value of each element
print('abs:', np.abs(np.array([-1,-2,3])))

Add: [11 22 33 44]
Sub: [ 9 18 27 36]
Mul: [ 10  40  90 160]
Div: [10. 10. 10. 10.]
Floor Div: [10 10 10 10]
Mod: [0 0 0 0]
Power: [ 100  400  900 1600]
np.add: [11 22 33 44]
np.multiply: [ 10  40  90 160]
sqrt: [3.16227766 4.47213595 5.47722558 6.32455532]
exp: [ 2.71828183  7.3890561  20.08553692 54.59815003]
log: [2.30258509 2.99573227 3.40119738 3.68887945]
log2: [3.32192809 4.32192809 4.9068906  5.32192809]
log10: [1.         1.30103    1.47712125 1.60205999]
abs: [1 2 3]


## 8️⃣ Trigonometric Functions

In [ ]:
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# np.sin/cos/tan compute trig values element-wise (input in radians)
print('sin:', np.sin(angles))
print('cos:', np.cos(angles))
print('tan:', np.tan(angles))

# Inverse trig functions return angles in radians
print('arcsin:', np.arcsin(np.sin(angles)))
print('arccos:', np.arccos(np.cos(angles)))
print('arctan:', np.arctan(np.tan(angles)))

# np.degrees() / np.radians() convert between radians and degrees
print('Degrees:', np.degrees(angles))
print('Radians:', np.radians(np.degrees(angles)))

## 9️⃣ Statistical Operations

In [ ]:
arr = np.array([[4,7,2,1],[9,3,6,8]])
print('Array:\n', arr)

# np.sum() adds all elements; axis=0 collapses rows, axis=1 collapses columns
print('Sum total:', np.sum(arr))
print('Sum axis=0:', np.sum(arr, axis=0))
print('Sum axis=1:', np.sum(arr, axis=1))

# np.mean() arithmetic average; np.median() middle value
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))

# np.std() standard deviation — spread of data around mean
print('Std:', np.std(arr))

# np.var() variance — square of standard deviation
print('Var:', np.var(arr))

# np.min/max return smallest/largest element; argmin/argmax return its index
print('Min:', np.min(arr), 'at index:', np.argmin(arr))
print('Max:', np.max(arr), 'at index:', np.argmax(arr))

# np.ptp() peak-to-peak: max - min (range of values)
print('Range (ptp):', np.ptp(arr))

# np.percentile() returns value at given percentile (0–100)
print('25th percentile:', np.percentile(arr, 25))
print('75th percentile:', np.percentile(arr, 75))

# np.cumsum() running total; np.cumprod() running product
a = np.array([1,2,3,4,5])
print('Cumsum:', np.cumsum(a))
print('Cumprod:', np.cumprod(a))

# np.corrcoef() computes Pearson correlation coefficient matrix
x = np.array([1,2,3]); y = np.array([2,4,5])
print('Correlation:\n', np.corrcoef(x, y))

# np.cov() computes covariance matrix — measures joint variability
print('Covariance:\n', np.cov(x, y))

## 🔟 Linear Algebra

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# np.dot() or @ computes matrix multiplication (dot product)
print('Matrix Multiply:\n', np.dot(A, B))
print('Using @:\n', A @ B)

# np.linalg.det() calculates the determinant of a square matrix
print('Determinant:', np.linalg.det(A))

# np.linalg.inv() finds the inverse matrix (A * A_inv = I)
print('Inverse:\n', np.linalg.inv(A))

# np.linalg.eig() returns eigenvalues and eigenvectors
vals, vecs = np.linalg.eig(A)
print('Eigenvalues:', vals)
print('Eigenvectors:\n', vecs)

# np.linalg.svd() singular value decomposition — factorizes any matrix
U, S, Vt = np.linalg.svd(A)
print('SVD S:', S)

# np.linalg.norm() computes vector/matrix norm (default: Frobenius/Euclidean)
print('Norm:', np.linalg.norm(A))

# np.linalg.rank() returns the rank of a matrix (number of linearly independent rows/cols)
print('Rank:', np.linalg.matrix_rank(A))

# np.linalg.solve() solves the linear system Ax = b
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print('Solution x:', x)

# np.trace() computes sum of diagonal elements
print('Trace:', np.trace(A))

# np.linalg.qr() QR decomposition into orthogonal Q and upper-triangular R
Q, R = np.linalg.qr(A)
print('QR - Q:\n', Q)
print('QR - R:\n', R)

# np.cross() computes the cross product of two 3D vectors
v1 = np.array([1,0,0]); v2 = np.array([0,1,0])
print('Cross product:', np.cross(v1, v2))

# np.inner() inner product of two vectors (generalized dot product)
print('Inner:', np.inner(np.array([1,2]), np.array([3,4])))

# np.outer() outer product — creates matrix from two 1D vectors
print('Outer:\n', np.outer(np.array([1,2]), np.array([3,4])))

## 1️⃣1️⃣ Broadcasting

In [ ]:
# Broadcasting allows arithmetic between arrays of different shapes — NumPy stretches smaller array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([10, 20, 30])   # shape (3,) broadcast across rows
print('Add row broadcast:\n', a + b)

# Column vector (3,1) broadcasts across columns
c = np.array([[10],[20],[30]])
print('Add col broadcast:\n', a + c)

# Scalar broadcast — applies same value to every element
print('Scalar broadcast:\n', a * 2)

# Broadcasting with different dims — shape (3,1) + shape (1,3) = shape (3,3)
r = np.array([[1],[2],[3]])
col = np.array([[10,20,30]])
print('2D broadcast:\n', r + col)

## 1️⃣2️⃣ Sorting & Searching

In [ ]:
arr = np.array([3,1,4,1,5,9,2,6,5])

# np.sort() returns a sorted copy (ascending by default)
print('Sorted:', np.sort(arr))

# np.argsort() returns indices that would sort the array
print('Argsort:', np.argsort(arr))

# np.sort with axis on 2D
m = np.array([[3,1,2],[9,7,8]])
print('Sort axis=1:\n', np.sort(m, axis=1))
print('Sort axis=0:\n', np.sort(m, axis=0))

# np.argmax/argmin return index of max/min value
print('Argmax:', np.argmax(arr), '| Argmin:', np.argmin(arr))

# np.searchsorted() finds insertion index to keep array sorted (binary search)
a = np.array([1,2,4,5,6])
print('Searchsorted:', np.searchsorted(a, 3))

# np.unique() returns sorted unique elements; return_counts for frequency
u, counts = np.unique(arr, return_counts=True)
print('Unique:', u)
print('Counts:', counts)

# np.partition() rearranges so k-th element is where it would be if sorted
print('Partition k=3:', np.partition(arr, 3))

## 1️⃣3️⃣ Set Operations

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])

# np.union1d() returns sorted unique elements from both arrays
print('Union:', np.union1d(a, b))

# np.intersect1d() returns elements common to both arrays
print('Intersection:', np.intersect1d(a, b))

# np.setdiff1d() returns elements in a that are NOT in b
print('Difference a-b:', np.setdiff1d(a, b))

# np.setxor1d() symmetric difference — elements in either but not both
print('Symmetric Diff:', np.setxor1d(a, b))

# np.in1d() / np.isin() tests membership of each element of a in b
print('in1d:', np.in1d(a, b))
print('isin:', np.isin(a, b))

## 1️⃣4️⃣ Logical & Comparison Operations

In [ ]:
a = np.array([1,0,1,0,1])
b = np.array([1,1,0,0,1])

# np.logical_and/or/not/xor apply boolean logic element-wise
print('AND:', np.logical_and(a, b))
print('OR:', np.logical_or(a, b))
print('NOT:', np.logical_not(a))
print('XOR:', np.logical_xor(a, b))

# np.all() returns True only if ALL elements are True
print('all > 0:', np.all(a > 0))

# np.any() returns True if AT LEAST ONE element is True
print('any > 0:', np.any(a > 0))

# Comparison operators return boolean arrays element-wise
arr = np.array([5,3,8,1,9])
print('> 4:', arr > 4)
print('== 8:', arr == 8)
print('<= 5:', arr <= 5)

# np.equal, np.greater etc. are ufunc equivalents of ==, >, etc.
print('np.equal:', np.equal(arr, np.array([5,3,8,2,9])))

# np.isnan/isinf/isfinite detect special floating point values
x = np.array([1.0, np.nan, np.inf, -np.inf, 5.0])
print('isnan:', np.isnan(x))
print('isinf:', np.isinf(x))
print('isfinite:', np.isfinite(x))

## 1️⃣5️⃣ Bitwise Operations

In [ ]:
a = np.array([12, 10, 15], dtype=np.uint8)  # 1100, 1010, 1111 in binary
b = np.array([10, 6, 9], dtype=np.uint8)

# np.bitwise_and: AND each bit pair — both must be 1 to produce 1
print('Bitwise AND:', np.bitwise_and(a, b))

# np.bitwise_or: OR each bit pair — at least one must be 1
print('Bitwise OR:', np.bitwise_or(a, b))

# np.bitwise_xor: XOR — bits differ → 1, same → 0
print('Bitwise XOR:', np.bitwise_xor(a, b))

# np.invert: flips all bits (bitwise NOT)
print('Invert:', np.invert(a))

# np.left_shift: shifts bits left by n (equivalent to multiplying by 2^n)
print('Left shift by 2:', np.left_shift(a, 2))

# np.right_shift: shifts bits right by n (equivalent to floor dividing by 2^n)
print('Right shift by 1:', np.right_shift(a, 1))

## 1️⃣6️⃣ String Operations (numpy.char)

In [ ]:
# NumPy has a char module for vectorized string operations on arrays
names = np.array(['alice', 'bob', 'charlie'])

# np.char.upper() / lower() converts case for every string element
print('Upper:', np.char.upper(names))
print('Lower:', np.char.lower(names))

# np.char.capitalize() capitalizes first letter of each string
print('Capitalize:', np.char.capitalize(names))

# np.char.add() concatenates two string arrays element-wise
domain = np.array(['@gmail.com','@yahoo.com','@hotmail.com'])
print('Email:', np.char.add(names, domain))

# np.char.multiply() repeats each string n times
print('Repeat:', np.char.multiply(names, 2))

# np.char.find() returns starting index of substring (-1 if not found)
print('Find "li":', np.char.find(names, 'li'))

# np.char.startswith/endswith checks prefix/suffix for each element
print('Starts with a:', np.char.startswith(names, 'a'))

# np.char.split() splits each string by delimiter
csv = np.array(['a,b,c', 'x,y,z'])
print('Split:', np.char.split(csv, ','))

# np.char.replace() replaces occurrences of a substring
print('Replace:', np.char.replace(names, 'a', '@'))

## 1️⃣7️⃣ Random Module

In [ ]:
# np.random.seed() sets the random seed for reproducibility
np.random.seed(42)

# np.random.rand() uniform distribution in [0, 1)
print('rand:', np.random.rand(3))

# np.random.randn() standard normal distribution (mean=0, std=1)
print('randn:', np.random.randn(3))

# np.random.randint() random integers between low (incl) and high (excl)
print('randint:', np.random.randint(1, 10, size=5))

# np.random.uniform() floats drawn uniformly between low and high
print('uniform:', np.random.uniform(1, 5, size=4))

# np.random.normal() samples from normal distribution with given mean and std
print('normal:', np.random.normal(loc=0, scale=1, size=4))

# np.random.choice() samples elements from an array with or without replacement
print('choice:', np.random.choice([10,20,30,40,50], size=3, replace=False))

# np.random.shuffle() randomly shuffles array in-place
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print('shuffle:', arr)

# np.random.permutation() returns a shuffled COPY (doesn't modify original)
print('permutation:', np.random.permutation([1,2,3,4,5]))

# np.random.binomial() simulates coin flips — n trials, p probability
print('binomial:', np.random.binomial(n=10, p=0.5, size=5))

# np.random.poisson() counts of rare events in an interval (lambda = rate)
print('poisson:', np.random.poisson(lam=3, size=5))

# np.random.exponential() models time between events in Poisson process
print('exponential:', np.random.exponential(scale=2.0, size=4))

## 1️⃣8️⃣ Copying: View vs Copy

In [ ]:
a = np.array([1,2,3,4,5])

# View (shallow copy) — shares memory with original; modifying view changes original
view = a[1:4]
view[0] = 99
print('After view modify, original:', a)  # original changed!

# .copy() creates an independent deep copy — changes do NOT affect original
a = np.array([1,2,3,4,5])
cp = a.copy()
cp[0] = 99
print('After copy modify, original:', a)  # original unchanged

# np.may_share_memory() checks if two arrays share memory
print('Shares memory:', np.may_share_memory(a, view))
print('Copy shares memory:', np.may_share_memory(a, cp))

## 1️⃣9️⃣ Input/Output Operations

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

# np.save() saves array to binary .npy file; np.load() reads it back
np.save('/tmp/my_array.npy', arr)
loaded = np.load('/tmp/my_array.npy')
print('Loaded from .npy:', loaded)

# np.savez() saves multiple arrays to compressed .npz file
np.savez('/tmp/multi.npz', a=arr, b=arr*2)
data = np.load('/tmp/multi.npz')
print('From npz - a:', data['a'])
print('From npz - b:', data['b'])

# np.savetxt() saves array as plain text/CSV readable by humans
np.savetxt('/tmp/data.csv', arr, delimiter=',', fmt='%d')

# np.loadtxt() loads numeric data from a text file
txt = np.loadtxt('/tmp/data.csv', delimiter=',')
print('From CSV:', txt)

# np.genfromtxt() handles missing values in text files gracefully
import io
s = b'1,2,3\n4,,6'   # missing middle value
gen = np.genfromtxt(io.BytesIO(s), delimiter=',', filling_values=0)
print('Genfromtxt:', gen)

## 2️⃣0️⃣ Advanced Indexing & Fancy Tricks

In [ ]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

# np.take() picks elements at given indices along an axis
print('take:', np.take(arr, [0,2], axis=0))

# np.put() places values at specific indices in the flattened array
a = np.arange(9).reshape(3,3)
np.put(a, [0, 4, 8], [-1,-2,-3])
print('after put:\n', a)

# np.diag() extracts diagonal or constructs diagonal matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Diagonal:', np.diag(mat))
print('Diag matrix:\n', np.diag([1,2,3]))

# np.tril/triu return lower/upper triangular portions of a matrix
print('Lower tri:\n', np.tril(mat))
print('Upper tri:\n', np.triu(mat))

# np.roll() shifts array elements along an axis (wraps around)
a = np.array([1,2,3,4,5])
print('Roll +2:', np.roll(a, 2))
print('Roll -1:', np.roll(a, -1))

# np.flip() reverses elements along a given axis
print('Flip:', np.flip(a))

# np.tile() repeats array n times along each axis to build larger array
print('Tile:', np.tile(np.array([1,2]), 3))

# np.repeat() repeats each element n times (not the whole array)
print('Repeat:', np.repeat(np.array([1,2,3]), 3))

## 2️⃣1️⃣ Structured Arrays & Record Arrays

In [ ]:
# Structured array holds heterogeneous data types per field — like a database table
dt = np.dtype([('name','U10'), ('age',np.int32), ('score',np.float64)])
data = np.array([('Alice',25,95.5),('Bob',30,88.0),('Carol',22,91.3)], dtype=dt)
print('Structured array:', data)
print('Names:', data['name'])
print('Scores > 90:', data[data['score'] > 90])

# np.sort on structured array by a field
sorted_data = np.sort(data, order='score')
print('Sorted by score:', sorted_data)

## 2️⃣2️⃣ Memory Layout & Strides

In [ ]:
# C-contiguous (row-major) is default in NumPy — rows stored consecutively
a_c = np.array([[1,2,3],[4,5,6]], order='C')
print('C-order strides:', a_c.strides)   # (bytes to next row, bytes to next col)
print('C-contiguous:', a_c.flags['C_CONTIGUOUS'])

# F-contiguous (column-major like FORTRAN) — columns stored consecutively
a_f = np.array([[1,2,3],[4,5,6]], order='F')
print('F-order strides:', a_f.strides)
print('F-contiguous:', a_f.flags['F_CONTIGUOUS'])

# np.ascontiguousarray() ensures C-contiguous memory layout
cont = np.ascontiguousarray(a_f)
print('Made contiguous:', cont.flags['C_CONTIGUOUS'])

# Strides define byte steps to move along each dimension
arr = np.arange(12, dtype=np.float64).reshape(3,4)
print('Strides (bytes):', arr.strides)  # (32, 8) = (4 cols * 8 bytes, 8 bytes)

## 2️⃣3️⃣ Polynomial Operations

In [ ]:
# np.poly1d() creates a polynomial object from coefficient array
p = np.poly1d([2, -3, 1])   # 2x^2 - 3x + 1
print('Polynomial:', p)
print('At x=2:', p(2))

# np.roots() finds roots (zeros) of a polynomial
print('Roots:', np.roots([2,-3,1]))

# np.polyfit() fits polynomial of given degree to data (least squares)
x = np.array([0,1,2,3,4])
y = np.array([1,3,7,13,21])
coeffs = np.polyfit(x, y, 2)
print('Polyfit coeffs:', coeffs)

# np.polyval() evaluates polynomial at given x values
print('Polyval at x=5:', np.polyval(coeffs, 5))

# Polynomial addition, subtraction, multiplication, division
p1 = np.poly1d([1,2]); p2 = np.poly1d([1,-3,2])
print('Add:', np.polyadd(p1,p2))
print('Mul:', np.polymul(p1,p2))
print('Div:', np.polydiv(p2,p1))

# Differentiate and integrate polynomial
print('Derivative:', p.deriv())
print('Integral:', p.integ())

## 2️⃣4️⃣ FFT (Fast Fourier Transform)

In [ ]:
# np.fft.fft() transforms signal from time domain to frequency domain
signal = np.array([1,2,3,4,3,2,1,0])
fft_result = np.fft.fft(signal)
print('FFT:', fft_result)

# np.fft.ifft() inverse FFT — converts back from frequency to time domain
reconstructed = np.fft.ifft(fft_result)
print('iFFT (real):', reconstructed.real)

# np.fft.fftfreq() returns sample frequencies for FFT result
freqs = np.fft.fftfreq(len(signal), d=1.0)
print('Frequencies:', freqs)

# np.fft.fftshift() shifts zero-frequency to center of spectrum
print('FFT shift:', np.fft.fftshift(fft_result))

# np.fft.rfft() FFT for real-valued signals (more efficient, half output)
print('rFFT:', np.fft.rfft(signal))

# np.fft.fft2() 2D FFT used in image processing
img = np.random.rand(4,4)
print('2D FFT shape:', np.fft.fft2(img).shape)

## 2️⃣5️⃣ Masked Arrays

In [ ]:
import numpy.ma as ma

# Masked arrays hide certain values from computations — useful for missing data
data = np.array([1, 2, -999, 4, -999, 6])
mask = data == -999   # mark -999 as invalid/missing
masked = ma.masked_array(data, mask=mask)
print('Masked array:', masked)

# Operations ignore masked values automatically
print('Mean (ignores masked):', masked.mean())
print('Sum (ignores masked):', masked.sum())

# ma.masked_where() creates mask based on a condition
arr = np.array([1,2,3,4,5,6])
m = ma.masked_where(arr % 2 == 0, arr)  # mask even numbers
print('Mask evens:', m)

# .filled() replaces masked values with a fill value
print('Filled:', m.filled(fill_value=0))

# ma.compressed() returns only the unmasked data as a 1D array
print('Compressed:', m.compressed())

## 2️⃣6️⃣ Matrix Class (np.matrix)

In [ ]:
# np.matrix is a 2D subclass where * means matrix multiply (deprecated; prefer @)
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[5,6],[7,8]])

# * operator does matrix multiplication on np.matrix objects
print('Matrix mul (*):\n', A * B)

# .I returns the matrix inverse
print('Inverse (.I):\n', A.I)

# .T returns the transpose
print('Transpose (.T):\n', A.T)

# .H returns conjugate transpose (Hermitian) — same as .T for real matrices
print('Hermitian (.H):\n', A.H)

# np.matrix is deprecated — modern NumPy recommends ndarray + @ operator
print('Note: prefer np.ndarray with @ operator over np.matrix')

## 2️⃣7️⃣ Universal Functions (ufuncs) & vectorize

In [ ]:
# np.vectorize() converts a Python function to operate element-wise on arrays
def grade(score):
    if score >= 90: return 'A'
    elif score >= 80: return 'B'
    elif score >= 70: return 'C'
    else: return 'F'

vgrade = np.vectorize(grade)
scores = np.array([95, 82, 73, 60])
print('Grades:', vgrade(scores))

# np.frompyfunc() creates a ufunc from a Python function — returns object array
add_one = np.frompyfunc(lambda x: x+1, 1, 1)
print('frompyfunc:', add_one(np.array([1,2,3])))

# ufunc .reduce() applies operation cumulatively along an axis (like functools.reduce)
print('add.reduce:', np.add.reduce([1,2,3,4,5]))

# ufunc .accumulate() running cumulative results (like cumsum for np.add)
print('add.accumulate:', np.add.accumulate([1,2,3,4,5]))

# ufunc .outer() computes outer product using the ufunc operation
print('add.outer:\n', np.add.outer([1,2,3],[10,20]))

# ufunc .at() performs unbuffered operation at specific indices (in-place)
a = np.array([1,2,3,4])
np.add.at(a, [0,2], 10)
print('add.at [0,2]+=10:', a)

## 2️⃣8️⃣ Datetime & Timedelta

In [ ]:
# np.datetime64 stores dates with specified resolution (D=day, M=month, Y=year)
d1 = np.datetime64('2024-01-15')
d2 = np.datetime64('2024-12-31')
print('Date:', d1, '| Type:', d1.dtype)

# Arithmetic on dates returns np.timedelta64 — the duration between dates
diff = d2 - d1
print('Days between:', diff)

# np.arange with dates generates a sequence of dates
week = np.arange('2024-01-01','2024-01-08', dtype='datetime64[D]')
print('Week:', week)

# np.datetime64 with time resolution (h=hours, m=minutes, s=seconds)
dt = np.datetime64('2024-01-15T14:30:00')
print('Datetime:', dt)

# Adding timedelta to a date
future = d1 + np.timedelta64(100, 'D')
print('100 days later:', future)

# Convert datetime64 to Python datetime
import datetime
py_date = d1.astype('datetime64[ms]').astype(datetime.datetime)
print('Python datetime:', py_date)

## 2️⃣9️⃣ Miscellaneous Useful Functions

In [ ]:
# np.clip() limits values in array to a specified [min, max] range
arr = np.array([1, 5, 10, 15, 20])
print('Clip [5,15]:', np.clip(arr, 5, 15))

# np.round() / np.floor() / np.ceil() / np.trunc() round in different ways
x = np.array([1.4, 1.5, 2.6, -1.5])
print('round:', np.round(x))
print('floor:', np.floor(x))
print('ceil:', np.ceil(x))
print('trunc:', np.trunc(x))

# np.sign() returns -1, 0, or 1 based on sign of each element
print('sign:', np.sign(np.array([-5,0,3])))

# np.diff() computes difference between consecutive elements
a = np.array([1,4,9,16,25])
print('diff:', np.diff(a))
print('diff 2nd order:', np.diff(a, n=2))

# np.gradient() estimates derivative using central differences
print('gradient:', np.gradient(a))

# np.interp() 1D linear interpolation at new x points
xp = [0, 1, 2]; fp = [0, 1, 4]
print('interp at 0.5:', np.interp(0.5, xp, fp))

# np.digitize() assigns each value to a bin — returns bin index
vals = np.array([0.5, 1.5, 2.5, 3.5])
bins = np.array([1, 2, 3])
print('digitize:', np.digitize(vals, bins))

# np.histogram() computes histogram — returns counts and bin edges
counts, edges = np.histogram(np.random.randn(1000), bins=10)
print('Histogram counts:', counts)

# np.meshgrid() generates coordinate grids — essential for 3D plots
x = np.array([1,2,3]); y = np.array([4,5])
X, Y = np.meshgrid(x, y)
print('Meshgrid X:\n', X)
print('Meshgrid Y:\n', Y)

# np.column_stack() joins 1D arrays as columns into 2D matrix
a = np.array([1,2,3]); b = np.array([4,5,6])
print('column_stack:\n', np.column_stack([a,b]))

# np.char.zfill() zero-pads numeric strings
nums = np.array(['5','42','100'])
print('zfill:', np.char.zfill(nums, 5))

---
## 🎉 Summary Table

| Category | Key Functions |
|---|---|
| **Array Creation** | `array, zeros, ones, full, eye, arange, linspace, random.*` |
| **Attributes** | `ndim, shape, size, dtype, itemsize, nbytes` |
| **Reshape** | `reshape, flatten, ravel, transpose, expand_dims, squeeze` |
| **Join/Split** | `concatenate, vstack, hstack, stack, split, hsplit, vsplit` |
| **Math** | `add, subtract, multiply, divide, sqrt, exp, log, abs` |
| **Trig** | `sin, cos, tan, arcsin, arccos, arctan, degrees, radians` |
| **Statistics** | `sum, mean, std, var, min, max, cumsum, percentile, corrcoef` |
| **Linear Algebra** | `dot, det, inv, eig, svd, solve, norm, qr, cross` |
| **Sort/Search** | `sort, argsort, argmax, unique, searchsorted, partition` |
| **Sets** | `union1d, intersect1d, setdiff1d, setxor1d, isin` |
| **Logic** | `logical_and/or/not/xor, all, any, isnan, isinf` |
| **Random** | `seed, rand, randn, randint, choice, shuffle, normal` |
| **I/O** | `save, load, savez, savetxt, loadtxt, genfromtxt` |
| **FFT** | `fft, ifft, rfft, fft2, fftfreq, fftshift` |
| **Masked** | `ma.masked_array, masked_where, compressed, filled` |
| **Strings** | `char.upper, char.lower, char.add, char.find, char.split` |
| **Misc** | `clip, round, diff, gradient, interp, histogram, meshgrid` |